version: "3"
services:
  fidni:
    build: .
    image: noclipsoul/fidni
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: fidniDB
      DATABASE_HOST: fidniDB
      DATABASE_PORT: 5432
      DATABASE_NAME: fidni
      DATABASE_USERNAME: fidni
      DATABASE_PASSWORD: fidni@ibsar123
      JWT_SECRET: I/+rkXaLbhgWkLBOpKJGbQ==
      ADMIN_JWT_SECRET: xxgcoJ6iMcpbILzSIz7ghw==
      APP_KEYS: 5P8FzTkv1IrIKtKhOEuYLA==,wGTjH7fdonR4TP9Fwaqs/w==,PW/Lg1TkgyvzA0Y1BXPP>
      NODE_ENV: production

    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 50s
      restart_policy:
        condition: on-failure

    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - fidniDB

  fidniDB:
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: fidni
      POSTGRES_PASSWORD: fidni@ibsar123
      POSTGRES_DB: fidni
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  strapi-data:
