version: "3"
services:
  fidni:
 
    build: .
    image: noclipsoul/fidni
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: fidniDB
      DATABASE_PORT: 
      DATABASE_NAME: fidniDB
      DATABASE_USERNAME: fidni
      DATABASE_PASSWORD: fidni@ibsar123
      JWT_SECRET: I/+rkXaLbhgWkLBOpKJGbQ==
      ADMIN_JWT_SECRET: xxgcoJ6iMcpbILzSIz7ghw==
      APP_KEYS: 5P8FzTkv1IrIKtKhOEuYLA==,wGTjH7fdonR4TP9Fwaqs/w==,PW/Lg1TkgyvzA0Y1BXPP>
      NODE_ENV: production
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
   
    depends_on:
      - fidniDB

  fidniDB:
   
   # platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: fidniDB
      POSTGRES_PASSWORD: fidni@ibsar123
      POSTGRES_DB: fidni
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    

volumes:
  strapi-data:

