version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: fidnidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fidni@ibsar123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  strapi:
    build: .
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: fidnidb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: fidni@ibsar123
    ports:
      - "1338:1338"
    depends_on:
      - postgres

volumes:
  pgdata:
